Main\AbstractBundle\Entity\Menu:
    type: entity
    table: menu
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 225
            fixed: false
            comment: ''
        link:
            type: string
            nullable: false
            length: 225
            fixed: false
            comment: ''
        alias:
            type: string
            nullable: false
            length: 225
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
